version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:9000"
    environment:
      - DEBUG=False
      - DATABASE_URL=postgresql://ahmet21:diclem2121.@165.227.130.23:5432/fxdb
      - REDIS_URL=redis://redis:9379/0
    depends_on:
      - redis
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  redis:
    image: redis:alpine
    ports:
      - "9379:6379"

  nginx:
    image: nginx:alpine
    ports:
      - "9080:80"
      - "9443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - /etc/ssl/certs:/etc/ssl/certs
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
