version: '3.8'

services:
  web:
    build: .
    container_name: django_web
    ports:
      - "9000:9000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings
      - DEBUG=False
      - ALLOWED_HOSTS=apphane.com.tr,165.227.130.23,localhost,127.0.0.1
      - DATABASE_URL=postgresql://ahmet21:diclem2121@165.227.130.23:5432/fxdb
    volumes:
      - ./:/app
      - ./media:/app/media
      - ./static:/app/static
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn config.wsgi:application --bind 0.0.0.0:9000 --workers 3 --timeout 120 --log-level info"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
