# Generated by Django 5.2.5 on 2025-08-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50, verbose_name='Sürüm')),
                ('channel', models.CharField(choices=[('test', 'Test'), ('stable', 'Kararlı')], default='stable', max_length=10, verbose_name='Kanal')),
                ('file', models.FileField(upload_to='releases/', verbose_name='Dosya')),
                ('file_size', models.BigIntegerField(verbose_name='Dosya Boyutu (Byte)')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA256 Hash')),
                ('changelog_markdown', models.TextField(blank=True, verbose_name='Değişiklik Listesi (Markdown)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('published_at', models.DateTimeField(auto_now_add=True, verbose_name='Yayınlanma Tarihi')),
                ('download_count', models.PositiveIntegerField(default=0, verbose_name='İndirme Sayısı')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='catalog.application', verbose_name='Uygulama')),
            ],
            options={
                'verbose_name': 'Sürüm',
                'verbose_name_plural': 'Sürümler',
                'ordering': ['-published_at'],
                'unique_together': {('application', 'version')},
            },
        ),
    ]
