# Generated by Django 5.2.5 on 2025-08-22 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Uygulama Adı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('short_description', models.CharField(max_length=300, verbose_name='Kısa Açıklama')),
                ('description_markdown', models.TextField(verbose_name='Detaylı Açıklama (Markdown)')),
                ('tags', models.CharField(blank=True, help_text='Virgülle ayırın', max_length=200, verbose_name='Etiketler')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='catalog.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Uygulama',
                'verbose_name_plural': 'Uygulamalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
