# Generated by Django 5.2.5 on 2025-08-22 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/images/', verbose_name='Uygulama Resmi'),
        ),
        migrations.AddField(
            model_name='application',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='apps/docs/', verbose_name='PDF Döküman'),
        ),
        migrations.AddField(
            model_name='application',
            name='screenshot1',
            field=models.ImageField(blank=True, null=True, upload_to='apps/screenshots/', verbose_name='Ekran Görüntüsü 1'),
        ),
        migrations.AddField(
            model_name='application',
            name='screenshot2',
            field=models.ImageField(blank=True, null=True, upload_to='apps/screenshots/', verbose_name='Ekran Görüntüsü 2'),
        ),
        migrations.AddField(
            model_name='application',
            name='screenshot3',
            field=models.ImageField(blank=True, null=True, upload_to='apps/screenshots/', verbose_name='Ekran Görüntüsü 3'),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi'),
        ),
        migrations.AddField(
            model_name='application',
            name='view_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Görüntülenme Sayısı'),
        ),
        migrations.AddField(
            model_name='application',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube Video Linki'),
        ),
    ]
