# Generated by Django 5.2.5 on 2025-08-22 23:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreelancerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Ad Soyad')),
                ('email', models.EmailField(max_length=254, verbose_name='E-posta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(max_length=100, verbose_name='Şehir')),
                ('title', models.CharField(max_length=200, verbose_name='Uzmanlık Alanı')),
                ('experience_years', models.IntegerField(verbose_name='Deneyim Yılı')),
                ('skill_level', models.CharField(choices=[('beginner', 'Başlangıç'), ('intermediate', 'Orta'), ('advanced', 'İleri'), ('expert', 'Uzman')], max_length=20, verbose_name='Seviye')),
                ('skills', models.TextField(help_text='Virgülle ayırarak yazın', verbose_name='Teknik Yetenekler')),
                ('portfolio_url', models.URLField(blank=True, verbose_name='Portföy/Website')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('cv_file', models.FileField(blank=True, upload_to='careers/cvs/', verbose_name='CV Dosyası')),
                ('cover_letter', models.TextField(max_length=1000, verbose_name='Kapak Mektubu')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Başvuru Tarihi')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='İnceleme Tarihi')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='İnceleme Notları')),
            ],
            options={
                'verbose_name': 'Freelancer Başvurusu',
                'verbose_name_plural': 'Freelancer Başvuruları',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
                ('description', models.TextField(blank=True, verbose_name='Açıklama')),
                ('icon', models.CharField(default='fas fa-code', max_length=50, verbose_name='Icon Sınıfı')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Proje Kategorisi',
                'verbose_name_plural': 'Proje Kategorileri',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('bio', models.TextField(blank=True, max_length=500, verbose_name='Kısa Biyografi')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='careers/profiles/', verbose_name='Profil Resmi')),
                ('total_projects', models.IntegerField(default=0, verbose_name='Toplam Proje')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Toplam Kazanç')),
                ('rating', models.FloatField(default=5.0, verbose_name='Değerlendirme')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('is_available', models.BooleanField(default=True, verbose_name='Çalışmaya Uygun')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saatlik Ücret (TL)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='careers.freelancerapplication')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Freelancer Profili',
                'verbose_name_plural': 'Freelancer Profilleri',
                'ordering': ['-rating', '-total_projects'],
            },
        ),
        migrations.CreateModel(
            name='FreelancerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Proje Başlığı')),
                ('description', models.TextField(verbose_name='Proje Açıklaması')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('technologies', models.CharField(max_length=500, verbose_name='Kullanılan Teknolojiler')),
                ('requirements', models.TextField(blank=True, verbose_name='Gereksinimler')),
                ('deliverables', models.TextField(verbose_name='Teslim Edilecekler')),
                ('estimated_duration', models.CharField(max_length=100, verbose_name='Tahmini Süre')),
                ('budget_range', models.CharField(choices=[('under_1000', '1.000 TL altı'), ('1000_5000', '1.000 - 5.000 TL'), ('5000_10000', '5.000 - 10.000 TL'), ('10000_25000', '10.000 - 25.000 TL'), ('25000_50000', '25.000 - 50.000 TL'), ('over_50000', '50.000 TL üzeri')], max_length=20, verbose_name='Bütçe Aralığı')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='careers/projects/', verbose_name='Öne Çıkan Görsel')),
                ('demo_url', models.URLField(blank=True, verbose_name='Demo/Canlı Link')),
                ('github_url', models.URLField(blank=True, verbose_name='GitHub Repo')),
                ('status', models.CharField(choices=[('draft', 'Taslak'), ('published', 'Yayında'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi')], default='draft', max_length=20, verbose_name='Durum')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Öne Çıkan')),
                ('views', models.IntegerField(default=0, verbose_name='Görüntülenme')),
                ('offers_count', models.IntegerField(default=0, verbose_name='Teklif Sayısı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='careers.freelancerprofile')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='careers.projectcategory')),
            ],
            options={
                'verbose_name': 'Freelancer Projesi',
                'verbose_name_plural': 'Freelancer Projeleri',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='careers/project_images/', verbose_name='Görsel')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Açıklama')),
                ('order', models.IntegerField(default=0, verbose_name='Sıra')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='careers.freelancerproject')),
            ],
            options={
                'verbose_name': 'Proje Görseli',
                'verbose_name_plural': 'Proje Görselleri',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200, verbose_name='Müşteri Adı')),
                ('client_email', models.EmailField(max_length=254, verbose_name='Müşteri E-posta')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Müşteri Telefon')),
                ('company_name', models.CharField(blank=True, max_length=200, verbose_name='Firma Adı')),
                ('offer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Tutarı (TL)')),
                ('message', models.TextField(max_length=1000, verbose_name='Mesaj')),
                ('timeline', models.CharField(max_length=200, verbose_name='Zaman Çizelgesi')),
                ('status', models.CharField(choices=[('pending', 'Beklemede'), ('accepted', 'Kabul Edildi'), ('rejected', 'Reddedildi'), ('withdrawn', 'Geri Çekildi')], default='pending', max_length=20, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Teklif Tarihi')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Yanıtlanma Tarihi')),
                ('response_message', models.TextField(blank=True, verbose_name='Yanıt Mesajı')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='careers.freelancerproject')),
            ],
            options={
                'verbose_name': 'Proje Teklifi',
                'verbose_name_plural': 'Proje Teklifleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
