# Generated by Django 5.2.5 on 2025-08-23 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerproject',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_projects', to='accounts.freelancerprofile'),
        ),
    ]
