# Generated by Django 5.2.5 on 2025-08-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0002_alter_freelancerproject_freelancer'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancerproject',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Tamamlanma Tarihi'),
        ),
        migrations.AddField(
            model_name='freelancerproject',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='careers/projects/', verbose_name='Proje Görseli'),
        ),
        migrations.AddField(
            model_name='freelancerproject',
            name='project_url',
            field=models.URLField(blank=True, help_text='Canlı proje bağlantısı', verbose_name='Proje URL'),
        ),
    ]
